name: Run index.php

on:
  schedule:
    - cron: '22 6,20 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run index.php
        env:
          LOC_ACCOUNTS: ${{ secrets.LOC_ACCOUNTS }}
          TG_PUSH_KEY: ${{ secrets.TG_PUSH_KEY }}
        run: php index.php
